name: First_Workflow

on:
    push: 
          branches:
              - main

jobs:

    job1:
        runs-on: ubuntu-latest 
        steps: 
              - name: clone repository        
                uses: actions/checkout@v7                 
              - name: check clone   
                run: ls
    job2:
        runs-on: ubuntu-latest   
        needs: job1
        steps: 
              - name: List folders          
                run: ls -al
 
    job3:
        runs-on: ubuntu-latest   
        needs: 
           - job2
           - job5
        steps: 
              - name: List folders          
                run: docker --version
    job4:
        runs-on: ubuntu-latest   
        needs: 
           - job2
           - job5
        steps: 
              - name: List folders          
                run: docker --version
    job5:
        runs-on: ubuntu-latest   
        needs: job1
        steps: 
              - name: List folders          
                run: docker --version